name:                openwallet

dependencies:
- base >= 4.7 && < 5

executables:
  openwallet:
    main:                openwallet.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cryptonite
    - bytestring
